name: Contentful Migration Example

on:
  pull_request:
    types: [opened, synchronize, reopened, closed]
    branches:
      - "**"

jobs:
  build:
    runs-on: ubuntu-latest
    name: Contentful Migration Example
    steps:
    - name: Check out code into the directory
      uses: actions/checkout@v1
      
    - name: Contentful Migration
      id: migrate
      uses: ./
      with:
        delete_feature: false
        set_alias: true
        master_pattern: "prod-[DD].[MM].[YYYY]-[hh][mm][ss]"
        feature_pattern: "sandbox-[ticket]"
        version_field: version
        version_content_type: versionTracking
        migrations_dir: test-migrations
        space_id: ${{ secrets.SPACE_ID }}
        management_api_key: ${{ secrets.MANAGEMENT_API_KEY }}
      env:
        LOG_LEVEL: verbose